---
### CHECAGENS ###

#MOODLE DOWNLOAD?
- name: MOODLE> Verificando se o download do Moodle foi realizado
  stat:
    path: "{{ moodle_root_path }}/version.php"
  register: moodle_downloaded
  
#MOODLE ISTALADO?
- name: MOODLE> Verificando se o Moodle esta Instalado
  stat:
    path: "{{ moodle_root_path }}/config.php"
  register: moodle_installed

#MOODLE DATA | Pasta Criada?
- name: MOODLE> Verificando se a pasta MoodleData foi criada
  stat:
    path: "{{ moodle_dataroot_path }}"
  register: moodle_dataroot_created

#MOODLE ROOT | Pasta Criada?
- name: MOODLE> Verificando se a pasta do Site foi criada
  stat:
    path: "{{ moodle_root_path }}"
  register: moodle_wwwroot_created

#MOODLE PASTA ROOT | CRIACAO
- name: MOODLE> Criando pasta 
  file:
    path: "{{ moodle_root_path }}"
    state: directory
  when: moodle_wwwroot_created.stat.exists

#MOODLE DOWNLOAD DO MOODLE
- name: MOODLE-GIT> Fazendo Download do Moodle
  git:
    repo: "{{ moodle_git_repository }}"
    dest: "{{ moodle_root_path }}"
  register: moodle_cloned
  when:
  - not moodle_downloaded.stat.exists

#MOODLE PERMISSOES
- name: MOODLE> Alterando Permissoes das pastas do Site 
  file:
    path: "{{ moodle_root_path }}"
    state: directory
    recurse: yes
    owner: "{{ moodle_root_owner }}"
    group: "{{ moodle_root_group }}"
    mode: "{{ moodle_root_permissions }}"
  when: moodle_cloned.changed

- name: MOODLE> Alterando Permissoes dos arquivos do Site
  shell: "find {{ moodle_root_path }} -type f -exec chmod 0644 {} \\;"
  when: not moodle_installed.stat.exists
  changed_when: moodle_cloned.changed

#MOODLE CRIAR PASTA MOODLEDATA
- name: MOODLE> Crianda pasta MoodleData
  file:
    path: "{{ moodle_dataroot_path }}"
    state: directory
    owner: "{{ moodle_dataroot_user }}"
    group: "{{ moodle_dataroot_group }}"
    mode: "{{ moodle_dataroot_permissions }}"
  when: not moodle_dataroot_created.stat.exists




